- job:
    name: sandbox-ansible-lint
    description: Example ansible-lint job.
    pre-run: playbooks/ansible-lint/pre.yaml
    run: playbooks/ansible-lint/run.yaml
    nodesets:
      nodes:
        - name: controller
          label: ubuntu-xenial

- job:
    name: sandbox-ansible-syntax
    description: Example ansible-syntax job.
    pre-run: playbooks/ansible-syntax/pre.yaml
    run: playbooks/ansible-syntax/run.yaml
    nodesets:
      nodes:
        - name: controller
          label: ubuntu-xenial

- job:
    name: sandbox-hello-world
    description: Simple hello world job.
    run: playbooks/hello-world/run.yaml
    nodesets:
      nodes:
        - name: controller
          label: ubuntu-xenial

- project:
    name: openstack-dev/sandbox
    check:
      jobs:
        - sandbox-ansible-lint
        - sandbox-ansible-syntax
        - sandbox-hello-world
    gate:
      jobs:
        - sandbox-ansible-lint
        - sandbox-ansible-syntax
        - sandbox-hello-world
